name: Deploy

on:
  push:
    branches:
      - development

env:
  PATH_PROD: /home/actions-runner/projects/artfora23-frontend

jobs:
  deploy:
    runs-on: prod
    name: Production
    steps:
      - name: Git       
        working-directory: ${{env.PATH_PROD}}
        run: |
          git checkout -f
          git pull --rebase deploy development
      
      - name: Install Dependencies       
        working-directory: ${{env.PATH_PROD}}
        run: docker exec artfora-frontend npm i --legacy-peer-deps
        
      - name: Building frontend
        working-directory: ${{env.PATH_PROD}}
        run: docker exec artfora-frontend npm run build