name: Deploy

on:
  push:
    branches:
      - development

env:
  PATH_PROD: /home/dev/projects/artfora23-frontend

jobs:
  deploy:
    runs-on: dev23ArtforaFrontend
    name: Production
    steps:
      - name: Git       
        working-directory: ${{env.PATH_PROD}}
        run: |
          git checkout -f development
          git pull --rebase deploy development
      
      - name: Install dependencies and build
        working-directory: ${{env.PATH_PROD}}
        run: docker-compose restart frontend